import test from 'node:test';
import assert from 'node:assert/strict';
import { createHandRegistry, executeHandGraph, resumeHandGraph, hashValue } from '../src/hand-runtime.mjs';
import { HOLOGRAPHIC_FIELD_EXAMPLES, HOLOGRAPHIC_FIELD_GRAPH, HOLOGRAPHIC_FIELD_HANDS, makeHolographicFieldInitialState } from '../src/holographic-field.mjs';
const registry=createHandRegistry(HOLOGRAPHIC_FIELD_HANDS);
function run(id,primitives,callerKind='deterministic-program'){return executeHandGraph({registry,graph:HOLOGRAPHIC_FIELD_GRAPH,initialState:makeHolographicFieldInitialState({seed:20260915,formId:id,primitives,requestedState:'idle'}),context:{callerKind}})}
test('field is deterministic and caller-neutral',()=>{const a=run('beacon',HOLOGRAPHIC_FIELD_EXAMPLES.beacon,'human-ui'),b=run('beacon',HOLOGRAPHIC_FIELD_EXAMPLES.beacon,'mirror-deterministic');assert.equal(a.finalStateHash,b.finalStateHash);assert.equal(a.finalState.field.cellHash,b.finalState.field.cellHash)});
test('same runtime accepts unrelated forms instead of one hard-coded anatomy',()=>{const rows=Object.entries(HOLOGRAPHIC_FIELD_EXAMPLES).map(([id,p])=>run(id,p));assert.equal(new Set(rows.map(x=>x.finalState.field.cellHash)).size,rows.length);for(const row of rows){assert.equal(row.finalState.field.schema,'axm.holographic-field/v0.1');assert.equal(row.finalState.realizations.holographicFieldStateNative.renderer,'axm.vfx.state-native-holographic-field/v0.1');assert.ok(row.finalState.field.cellCount>500);assert.equal('ai' in row.finalState,false)}});
test('canonical cells can be edited at checkpoint and only descendants replay',()=>{const original=run('console',HOLOGRAPHIC_FIELD_EXAMPLES.console),checkpoint=original.checkpoints.find(x=>x.stageId==='sample-form-field');assert.ok(checkpoint);const cells=structuredClone(checkpoint.state.field.cells);cells[0][0]+=0.125;const expected=hashValue(cells),resumed=resumeHandGraph({registry,graph:HOLOGRAPHIC_FIELD_GRAPH,checkpoint,edits:[{op:'set',path:['field','cells',0,0],value:cells[0][0]}],context:{callerKind:'human-ui'}});assert.deepEqual(resumed.executedStageIds,['emitter','scan-depth','signal-breakup','semantic-behavior','projection-motion','realize-field-state-native']);assert.equal(resumed.finalState.field.cellHash,expected);assert.notEqual(original.finalState.field.cellHash,resumed.finalState.field.cellHash)});
test('renderer keeps canonical field separate from rebuildable GPU realization',()=>{const r=run('sentinel',HOLOGRAPHIC_FIELD_EXAMPLES.sentinel).finalState.realizations.holographicFieldStateNative;assert.equal(r.workingSet.canonicalFieldRetained,true);assert.equal(r.workingSet.derivedGpuDataRebuildable,true);assert.equal(r.workingSet.fieldBufferBuildPolicy,'once-per-field-hash');assert.equal(r.workingSet.behaviorDeltaPolicy,'uniform-only');assert.ok(r.workingSet.modeledBufferBytes<1000000);assert.match(r.content,/g\.bufferData\(g\.ARRAY_BUFFER,packed,g\.STATIC_DRAW\)/);assert.match(r.content,/g\.drawArrays\(g\.POINTS,0,packed\.length\/stride\)/);assert.doesNotMatch(r.content,/head|torso|pelvis|arms|legs/) });
