import { deepClone, hashValue } from './hand-runtime.mjs';
import { emitterFieldHand, scanVolumeHand, breakupFieldHand, projectionMotionHand } from './volumetric-hologram-hands.mjs';

const TAU=Math.PI*2,PHI=(1+Math.sqrt(5))/2,MAX_CELLS=20000;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)));
const r6=v=>Number(Number(v).toFixed(6));
const v3=(v,f=[0,0,0])=>{const s=Array.isArray(v)&&v.length>=3?v:f;return s.slice(0,3).map(x=>r6(Number(x)||0))};
const norm=v=>{const n=Math.hypot(...v)||1;return v.map(x=>x/n)};
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
function hand(id,execute,description){return Object.freeze({schema:'axm.hand/v0.1',id,version:'0.1.0',deterministic:true,callerNeutral:true,network:'forbidden',description,execute})}
function cell(out,p,size=2,channel=0,phase=0,intensity=1){if(out.length>=MAX_CELLS)throw Error(`Holographic field exceeds ${MAX_CELLS} cells`);out.push([...v3(p),r6(clamp(size,.25,24)),Math.round(clamp(channel,0,15)),r6(((Number(phase)||0)%1+1)%1),r6(clamp(intensity,0,4))])}
function sample(out,p,k){const type=String(p?.type||''),center=v3(p.center),count=Math.round(clamp(p.count??240,8,5000));if(type==='sphere'||type==='ellipsoid'){const rr=v3(p.radii,[p.radius??.3,p.radius??.3,p.radius??.3]).map(x=>Math.abs(x)||.001);for(let i=0;i<count;i++){const t=(i+.5)/count,y=1-2*t,q=Math.sqrt(Math.max(0,1-y*y)),a=TAU*(i+k*.1732)/PHI;cell(out,[center[0]+Math.cos(a)*q*rr[0],center[1]+y*rr[1],center[2]+Math.sin(a)*q*rr[2]],p.size,p.channel,i/count,p.intensity)}return}
if(type==='capsule'){const a=v3(p.a),b=v3(p.b,[0,.5,0]),rad=Math.abs(clamp(p.radius??.05,.001,2)),axis=norm(b.map((x,i)=>x-a[i])),fb=Math.abs(axis[1])<.9?[0,1,0]:[1,0,0],u=norm(cross(axis,fb)),w=norm(cross(axis,u));for(let i=0;i<count;i++){const t=(i*.61803398875+k*.137)%1,ang=TAU*((i*.754877666+k*.193)%1),q=rad*(.82+.18*Math.sin((i+1)*1.71)),c=a.map((x,j)=>x+(b[j]-x)*t);cell(out,c.map((x,j)=>x+(u[j]*Math.cos(ang)+w[j]*Math.sin(ang))*q),p.size,p.channel,i/count,p.intensity)}return}
if(type==='ring'){const rad=Math.abs(clamp(p.radius??p.major??.35,.001,3)),minor=Math.abs(clamp(p.thickness??p.minor??.01,0,.8)),tilt=clamp(p.tilt??0,-Math.PI,Math.PI),ct=Math.cos(tilt),st=Math.sin(tilt);for(let i=0;i<count;i++){const a=TAU*i/count,b=TAU*((i*.381966+k*.071)%1),x=(rad+Math.cos(b)*minor)*Math.cos(a),y=Math.sin(b)*minor,z=(rad+Math.cos(b)*minor)*Math.sin(a);cell(out,[center[0]+x,center[1]+y*ct-z*st,center[2]+y*st+z*ct],p.size,p.channel,i/count,p.intensity)}return}
if(type==='box'){const h=v3(p.halfExtents,[.4,.25,.08]).map(x=>Math.abs(x)||.001);for(let i=0;i<count;i++){const face=i%6,u=((i*.618033+k*.11)%1)*2-1,w=((i*.754878+k*.17)%1)*2-1;const q=face===0?[h[0],u*h[1],w*h[2]]:face===1?[-h[0],u*h[1],w*h[2]]:face===2?[u*h[0],h[1],w*h[2]]:face===3?[u*h[0],-h[1],w*h[2]]:face===4?[u*h[0],w*h[1],h[2]]:[u*h[0],w*h[1],-h[2]];cell(out,q.map((x,j)=>x+center[j]),p.size,p.channel,i/count,p.intensity)}return}
if(type==='polyline'){const pts=(p.points||[]).map(x=>v3(x));if(pts.length<2)throw Error('polyline requires at least two points');for(let i=0;i<count;i++){const t=i/(count-1),s=t*(pts.length-1),j=Math.min(pts.length-2,Math.floor(s)),q=s-j;cell(out,pts[j].map((x,n)=>x+(pts[j+1][n]-x)*q),p.size,p.channel,t,p.intensity)}return}
if(type==='points'){for(const q of p.cells||[])cell(out,q.slice(0,3),q[3]??p.size,q[4]??p.channel,q[5]??0,q[6]??p.intensity);return}throw Error(`Unsupported holographic field primitive: ${type||'<missing>'}`)}

export const holographicFieldSampleHand=hand('fx.hologram.sample-form-field',(state)=>{const next=deepClone(state),source=next.field?.source;if(source?.schema!=='axm.holographic-form/v0.1'||!Array.isArray(source.primitives))throw Error('field.source axm.holographic-form/v0.1 required');if(source.primitives.length>128)throw Error('Too many holographic primitives');const cells=[];source.primitives.forEach((p,i)=>sample(cells,p,i));Object.assign(next.field,{schema:'axm.holographic-field/v0.1',cellStride:['x','y','z','size','channel','phase','intensity'],cells,cellCount:cells.length,cellHash:hashValue(cells)});return{state:next,evidence:{formId:source.id,primitiveCount:source.primitives.length,cellCount:cells.length,cellHash:next.field.cellHash}}},'Compile bounded arbitrary form primitives into an editable canonical holographic cell field.');

const PROFILES=Object.freeze({dormant:{visibility:.02,coherence:.08,pulse:0,breakup:.08,scan:0},reveal:{visibility:.78,coherence:.56,pulse:.72,breakup:.62,scan:1},materialize:{visibility:.82,coherence:.62,pulse:.65,breakup:.55,scan:1},idle:{visibility:1,coherence:1,pulse:.18,breakup:.14,scan:.28},focus:{visibility:1,coherence:1.08,pulse:.42,breakup:.08,scan:.6},alert:{visibility:1,coherence:1.14,pulse:.9,breakup:.42,scan:.88},collapse:{visibility:.18,coherence:.12,pulse:0,breakup:1,scan:.9}});
export const holographicFieldBehaviorHand=hand('fx.hologram.field-behavior',(state)=>{const next=deepClone(state),name=String(next.effect?.requestedState??next.effect?.activeState??'idle'),profile=PROFILES[name];if(!profile)throw Error(`Unknown holographic field state: ${name}`);next.effect.activeState=name;next.effect.profile=deepClone(profile);return{state:next,evidence:{activeState:name,profileHash:hashValue(profile)}}},'Resolve semantic projection state into renderer-neutral field behavior.');

export const holographicFieldWebglHand=hand('fx.hologram.field-state-native-webgl',(state)=>{const next=deepClone(state);if(!next.effect?.profile||!next.emitter||!next.motion||!Array.isArray(next.field?.cells)||!next.field.cells.length)throw Error('field renderer requires field, behavior, emitter and motion state');next.field.cellCount=next.field.cells.length;next.field.cellHash=hashValue(next.field.cells);const packed=next.field.cells.flat().map(Number),workingHash=hashValue(packed),canonicalHash=hashValue({effect:next.effect,field:next.field,emitter:next.emitter,fields:next.fields,motion:next.motion}),tint=next.effect.tint??[.16,.88,1],accent=next.effect.accent??[.55,.28,1],profile=next.effect.profile;
const V=`#version 300 es\nprecision highp float;layout(location=0)in vec3 P;layout(location=1)in float S;layout(location=2)in float C;layout(location=3)in float H;layout(location=4)in float I;uniform vec2 M;uniform float T,A,VIS,COH,BRK,PUL,PS;out float c,h,i,y,b;mat2 r(float a){float x=cos(a),s=sin(a);return mat2(x,-s,s,x);}float q(float n){return fract(sin(n)*43758.5453);}void main(){vec3 p=P;p.y+=sin(T*.78+H*6.283)*.01*(.35+PUL);p.xz=r(sin(T*.22)*.025+(M.x-.5)*.22)*p.xz;p.yz=r((M.y-.5)*-.09)*p.yz;float band=floor((p.y+1.3)*24.);float g=step(.93,q(band+floor(T*9.)*17.+H*43.))*BRK;p.x+=(q(band+H*73.)-.5)*.07*g;float d=max(.82,2.85-p.z);vec2 z=vec2(p.x*2.05/d,p.y*2.05/d);z.x/=max(1.,A*.72);gl_Position=vec4(z,0,1);gl_PointSize=max(1.,S*PS*(C==2.?1.45:C==3.?1.75:1.)*(1.35/d)*max(.6,COH));c=C;h=H;i=I;y=p.y;b=g;}`;
const F=`#version 300 es\nprecision highp float;out vec4 O;uniform float T,VIS,COH,PUL,SCN;uniform vec3 K,X;in float c,h,i,y,b;void main(){vec2 q=gl_PointCoord-.5;float d=length(q);if(d>.5)discard;float soft=pow(max(0.,1.-d*2.),1.35),scan=.78+.22*SCN*sin(y*112.-T*11.+h*6.283),m=clamp(mod(c,4.)/3.,0.,1.);vec3 col=mix(K,X,m*.68);if(c==2.)col=vec3(.82,1.,1.);float pulse=1.+PUL*.28*sin(T*(2.+h*2.)+h*12.);float a=soft*i*(.62+.38*COH)*scan*pulse*VIS*(1.-b*.7);O=vec4(col*a,a);}`;
const html=`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AXM Holographic Field</title><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#02040a}canvas{width:100%;height:100%;display:block}.tag{position:fixed;left:14px;bottom:12px;font:10px ui-monospace;color:#9ffcffaa}</style><canvas id="c"></canvas><div class="tag">FORM-NEUTRAL HOLOGRAPHIC FIELD</div><script type="module">const packed=new Float32Array(${JSON.stringify(packed)}),stride=7,profiles=${JSON.stringify(PROFILES)},tint=new Float32Array(${JSON.stringify(tint)}),accent=new Float32Array(${JSON.stringify(accent)}),c=document.querySelector('#c'),g=c.getContext('webgl2',{antialias:false,alpha:false,powerPreference:'high-performance'});if(!g)throw Error('WebGL2 required');const V=${JSON.stringify(V)},F=${JSON.stringify(F)};function sh(t,s){const x=g.createShader(t);g.shaderSource(x,s);g.compileShader(x);if(!g.getShaderParameter(x,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(x));return x}const P=g.createProgram();g.attachShader(P,sh(g.VERTEX_SHADER,V));g.attachShader(P,sh(g.FRAGMENT_SHADER,F));g.linkProgram(P);g.useProgram(P);const B=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,B);g.bufferData(g.ARRAY_BUFFER,packed,g.STATIC_DRAW);for(const[x,n,o]of[[0,3,0],[1,1,3],[2,1,4],[3,1,5],[4,1,6]]){g.enableVertexAttribArray(x);g.vertexAttribPointer(x,n,g.FLOAT,false,stride*4,o*4)}const U={};for(const n of['M','T','A','VIS','COH','BRK','PUL','SCN','PS','K','X'])U[n]=g.getUniformLocation(P,n);g.uniform3fv(U.K,tint);g.uniform3fv(U.X,accent);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE);const m={x:.5,y:.5};let state=${JSON.stringify(next.effect.activeState)},p=profiles[state]||profiles.idle;function resize(){const d=Math.min(devicePixelRatio||1,1.25);c.width=innerWidth*d;c.height=innerHeight*d;g.viewport(0,0,c.width,c.height)}addEventListener('resize',resize);addEventListener('pointermove',e=>{m.x=e.clientX/innerWidth;m.y=1-e.clientY/innerHeight});c.onclick=()=>{const s=['idle','focus','alert'];state=s[(s.indexOf(state)+1)%s.length];p=profiles[state]};function frame(now){g.clearColor(.002,.004,.011,1);g.clear(g.COLOR_BUFFER_BIT);g.uniform2f(U.M,m.x,m.y);g.uniform1f(U.T,now*.001);g.uniform1f(U.A,c.width/c.height);g.uniform1f(U.VIS,p.visibility);g.uniform1f(U.COH,p.coherence);g.uniform1f(U.BRK,p.breakup);g.uniform1f(U.PUL,p.pulse);g.uniform1f(U.SCN,p.scan);g.uniform1f(U.PS,Math.max(.8,c.height/700));g.drawArrays(g.POINTS,0,packed.length/stride);requestAnimationFrame(frame)}resize();requestAnimationFrame(frame);console.info('AXM holographic field',{canonicalHash:${JSON.stringify(canonicalHash)},fieldHash:${JSON.stringify(next.field.cellHash)},workingSetHash:${JSON.stringify(workingHash)},fieldBufferBuilds:1,behaviorDeltaPolicy:'uniform-only'});</script>`;
next.realizations??={};next.realizations.holographicFieldStateNative={mediaType:'text/html',renderer:'axm.vfx.state-native-holographic-field/v0.1',derivedFromStateHash:canonicalHash,workingSet:{schema:'axm.render-working-set/v0.1',policy:'form-neutral-holographic-field',canonicalFieldRetained:true,derivedGpuDataRebuildable:true,fieldBufferBuildPolicy:'once-per-field-hash',behaviorDeltaPolicy:'uniform-only',fieldHash:next.field.cellHash,workingSetHash:workingHash,canonicalCellCount:next.field.cellCount,pointCount:next.field.cellCount,modeledBufferBytes:packed.length*4},content:html};return{state:next,evidence:{renderer:'axm.vfx.state-native-holographic-field/v0.1',formId:next.field.source.id,fieldHash:next.field.cellHash,canonicalCellCount:next.field.cellCount,modeledBufferBytes:packed.length*4}}},'Realize any canonical holographic cell field as a reusable state-native GPU point working set.');

export const HOLOGRAPHIC_FIELD_HANDS=[holographicFieldSampleHand,emitterFieldHand,scanVolumeHand,breakupFieldHand,holographicFieldBehaviorHand,projectionMotionHand,holographicFieldWebglHand];
export const HOLOGRAPHIC_FIELD_GRAPH=Object.freeze({schema:'axm.hand-graph/v0.1',id:'fx.holographic-form-field-state-native',version:'0.1.0',stages:[{id:'sample-form-field',hand:'fx.hologram.sample-form-field',params:{}},{id:'emitter',hand:'fx.hologram.emitter-field',params:{originY:-.98,coneHeight:1.7,coneWidth:.72,floorRingRadius:.34,intensity:.9}},{id:'scan-depth',hand:'fx.hologram.scan-volume',params:{planes:7,speed:.22,thickness:.032}},{id:'signal-breakup',hand:'fx.hologram.breakup-volume',params:{bands:10,strength:.3}},{id:'semantic-behavior',hand:'fx.hologram.field-behavior',params:{}},{id:'projection-motion',hand:'fx.hologram.projection-motion',params:{revealMs:1450,collapseMs:900,idlePeriodMs:5000,floatAmplitude:.025,yawAmplitude:.045,shimmer:.2}},{id:'realize-field-state-native',hand:'fx.hologram.field-state-native-webgl',params:{}}]});
export const HOLOGRAPHIC_FIELD_EXAMPLES=Object.freeze({beacon:Object.freeze([{type:'sphere',center:[0,.08,0],radius:.29,count:620,size:2.05,channel:0,intensity:.82},{type:'ring',center:[0,.08,0],radius:.42,thickness:.012,tilt:.18,count:220,size:2.2,channel:1,intensity:.95}]),console:Object.freeze([{type:'box',center:[0,.08,0],halfExtents:[.52,.31,.055],count:780,size:1.8,channel:0,intensity:.72},{type:'polyline',points:[[-.42,.22,.07],[-.08,.22,.07],[.08,.02,.07],[.4,.02,.07]],count:260,size:2.4,channel:2,intensity:1}]),sentinel:Object.freeze([{type:'sphere',center:[0,.42,0],radius:.13,count:260,size:2.1,channel:2,intensity:.95},{type:'capsule',a:[0,.27,0],b:[0,-.26,0],radius:.11,count:430,size:1.95,channel:0,intensity:.78},{type:'capsule',a:[-.08,.1,0],b:[-.35,-.02,.02],radius:.045,count:190,size:1.8,channel:1,intensity:.75},{type:'capsule',a:[.08,.1,0],b:[.35,.08,-.02],radius:.045,count:190,size:1.8,channel:1,intensity:.75}])});
export function makeHolographicFieldInitialState({seed=1,formId='custom-form',primitives=HOLOGRAPHIC_FIELD_EXAMPLES.beacon,requestedState='idle',tint=[.16,.88,1],accent=[.55,.28,1]}={}){return{schema:'axm.holographic-field-state/v0.1',effect:{id:'fx.holographic-form-field',seed:Number(seed)>>>0,requestedState,activeState:requestedState,tint:deepClone(tint),accent:deepClone(accent),truthBoundary:'creative projection state; not physical volumetric light or matter'},field:{source:{schema:'axm.holographic-form/v0.1',id:String(formId),primitives:deepClone(primitives)}}}}
